name: mckinleyassociates
favicon: null
layout_spectrum: 0
typography_spectrum: 0.74399
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#2c2c2c'
    - '#8b8b8b'
    - '#c9c6b3'
    - '#fb493b'
  brandStrength: 0.9557618303224444
  lightness: 0.4325396849308163
  saturation: 0.8074066317640245
  rhythmicContrast: 0.8059234840329736
purpose: []
